# SonarCloud configuration
sonar.projectKey=mikitka-blr_parking-project
sonar.organization=mikitka-blr
sonar.host.url=https://sonarcloud.io

# Source directories
sonar.sources=src/main/java
sonar.exclusions=**/dto/**, **/model/**, **/mapper/**

# Java version
sonar.java.source=21

# Exclude duplications check for DTO and Model
sonar.cpd.exclusions=**/dto/**, **/model/**, **/mapper/**